name: Auto-build arr APKs

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Specific app to build'
        type: choice
        default: all
        options:
          - all
          - bazarr
          - sonarr
          - radarr
          - prowlarr

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  APPS_CONFIG: |
    {
      "bazarr":  { "upstream": "morpheus65535/bazarr",  "description": "Subtitle management" },
      "sonarr":  { "upstream": "Sonarr/Sonarr",         "description": "TV series management" },
      "radarr":  { "upstream": "Radarr/Radarr",         "description": "Movie management"   },
      "prowlarr":{ "upstream": "Prowlarr/Prowlarr",     "description": "Indexer management" }
    }

jobs:
  detect-updates:
    runs-on: ubuntu-latest
    outputs:
      apps_matrix: ${{ steps.check-apps.outputs.apps_matrix }}
      has_updates: ${{ steps.check-apps.outputs.has_updates }}

    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Check for app updates
      id: check-apps
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SELECTED_APP: ${{ github.event.inputs.app_name || 'all' }}
      run: bash ./scripts/check-apps.sh

  # Update APKBUILDs and commit changes
  update-apkbuilds:
    needs: detect-updates
    if: needs.detect-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect-updates.outputs.apps_matrix) }}
      max-parallel: 1
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Update APKBUILD for ${{ matrix.app }}
      run: |
        set -e

        apkbuild_path="${{ matrix.app }}/APKBUILD"
        new_version="${{ matrix.version }}"

        echo "Updating $apkbuild_path to version $new_version"

        sed -Ei \
          -e "s/^pkgver=.*/pkgver=${new_version}/" \
          -e "s/^pkgrel=.*/pkgrel=0/" \
          "$apkbuild_path"

        # Run abuild as the *current* UID/GID so ownership is preserved
        docker run --rm \
          -v "$PWD/${{ matrix.app }}":/work -w /work \
          alpine:edge sh -euo pipefail -c '
            apk add --no-cache alpine-sdk
            abuild checksum
          '
        sudo chown -R "$(id -u):$(id -g)" "${{ matrix.app }}"
        chmod -R u+w "${{ matrix.app }}"
    - name: Commit & tag
      run: |
        set -euo pipefail
        git config --global user.name  "Auto-APK CI"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add "${{ matrix.app }}/APKBUILD"

        # Commit if there are changes
        if ! git diff --cached --quiet; then
          echo "APKBUILD has been updated. Committing and pushing changes..."
          git commit -m "${{ matrix.app }}: bump to v${{ matrix.version }}"
          git pull --rebase --autostash origin "main"
          git push origin HEAD:"main"
        else
          echo "APKBUILD is already up-to-date. Nothing to commit."
        fi

        # --- FIX: Check if the tag already exists before creating it ---
        TAG_NAME="${{ matrix.app }}-v${{ matrix.version }}"
        if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          echo "Tag $TAG_NAME already exists. Skipping tag creation."
        else
          echo "Creating and pushing tag $TAG_NAME"
          git tag -a "$TAG_NAME" -m "Release ${{ matrix.app }} v${{ matrix.version }}"
          git push origin "$TAG_NAME" # More efficient to push just the one tag
        fi

  # Build APKs for updated apps
  build-apks:
    needs: [detect-updates, update-apkbuilds]
    if: needs.detect-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        app_data: ${{ fromJSON(needs.detect-updates.outputs.apps_matrix) }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Build APK for ${{ matrix.app_data.app }}
      env:
        KEY_NAME: ${{ secrets.KEY_NAME }}
        PRIVATE_KEY: ${{ secrets.PACKAGER_PRIVKEY }}
        TARGET_ARCH: x86_64
        APP_NAME: ${{ matrix.app_data.app }}
      run: bash ./scripts/build.sh

    - name: Upload ${{ matrix.app_data.app }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app_data.app }}-x86_64-apks
        path: ${{ matrix.app_data.app }}/out/*.apk
        retention-days: 30

  create-releases:
    needs: build-apks
    if: needs.detect-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect-updates.outputs.apps_matrix) }}

    steps:
    - name: Download ${{ matrix.app }} artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.app }}-x86_64-apks 
        path: artifacts

    - name: List downloaded APKs
      run: |
        echo "::group::Artifacts for ${{ matrix.app }}"
        find artifacts -name '*.apk' -printf '%P\n'
        echo "::endgroup::"

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        tag_name:  ${{ matrix.app }}-v${{ matrix.version }}
        name:      "${{ matrix.app }} v${{ matrix.version }} (Alpine x86_64)"
        draft:     false
        prerelease: false
        files:     artifacts/*.apk
        body: |
          ## ${{ matrix.app }} v${{ matrix.version }}

          **${{ matrix.description }}**

          Alpine Linux APK package (*x86_64*).

          ### Quick install
          ```bash
          apk add --allow-untrusted ${{ matrix.app }}-${{ matrix.version }}-r0.apk
          ```

          Built automatically from upstream release:  
          https://github.com/${{ matrix.upstream }}/releases/tag/${{ matrix.version }}
