name: Auto-build arr APKs

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Specific app to build'
        type: choice
        default: all
        options:
          - all
          - bazarr
          - sonarr
          - radarr
          - prowlarr

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  ARCHES: '["x86_64", "aarch64"]'
  APPS_CONFIG: |
    {
      "bazarr":  { "upstream": "morpheus65535/bazarr",  "description": "Subtitle management" },
      "sonarr":  { "upstream": "Sonarr/Sonarr",         "description": "TV series management" },
      "radarr":  { "upstream": "Radarr/Radarr",         "description": "Movie management"   },
      "prowlarr":{ "upstream": "Prowlarr/Prowlarr",     "description": "Indexer management" }
    }

jobs:
  detect-updates:
    runs-on: ubuntu-latest
    outputs:
      apps_matrix: ${{ steps.check-apps.outputs.apps_matrix }}
      has_updates: ${{ steps.check-apps.outputs.has_updates }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Check for app updates
      id: check-apps
      env:
        SELECTED_APP: ${{ github.event.inputs.app_name || 'all' }}
      run: bash ./scripts/check-apps.sh

  # Update APKBUILDs and commit changes
  update-apkbuilds:
    needs: detect-updates
    if: needs.detect-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect-updates.outputs.apps_matrix) }}
      max-parallel: 1
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Update APKBUILD for ${{ matrix.app }}
      run: |
        set -e
        
        apkbuild_path="${{ matrix.app }}/APKBUILD"
        new_version="${{ matrix.version }}"
        
        echo "Updating $apkbuild_path to version $new_version"
        
        # Update version and reset release number
        sed -Ei \
          -e "s/^pkgver=.*/pkgver=${new_version}/" \
          -e "s/^pkgrel=.*/pkgrel=0/" \
          "$apkbuild_path"

        # Update checksums using Alpine container
        docker run --rm \
          -v "$PWD/${{ matrix.app }}":/work -w /work \
          alpine:edge sh -euo pipefail -c \
            'apk add --no-cache alpine-sdk && abuild checksum'

    - name: Commit & tag
      run: |
        set -euo pipefail
        git config --global user.name  "Auto-APK CI"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add "${{ matrix.app }}/APKBUILD"
        git commit -m "${{ matrix.app }}: bump to v${{ matrix.version }}"

        # push branch first, then tag, then push tags
        git push origin HEAD:${{ github.ref_name }}
        git tag -a "${{ matrix.app }}-v${{ matrix.version }}" -m "Release ${{ matrix.app }} v${{ matrix.version }}"
        git push --tags

  # Build APKs for updated apps
  build-apks:
    needs: [detect-updates, update-apkbuilds]
    if: needs.detect-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        app_data: ${{ fromJSON(needs.detect-updates.outputs.apps_matrix) }}
        arch:     ${{ fromJSON('["x86_64","aarch64"]') }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Enable multi-arch emulation
      uses: docker/setup-qemu-action@v3

    - name: Validate secrets
      run: |
        if [ -z "${{ secrets.ABUILD_KEY_NAME }}" ] || [ -z "${{ secrets.ABUILD_PRIVATE_KEY }}" ]; then
          echo "Missing required secrets: ABUILD_KEY_NAME and ABUILD_PRIVATE_KEY"
          exit 1
        fi

    - name: Build APK for ${{ matrix.app_data.app }} on ${{ matrix.arch }}
      env:
        KEY_NAME: ${{ secrets.ABUILD_KEY_NAME }}
        PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
        ARCH: ${{ matrix.arch }}
        APP_NAME: ${{ matrix.app_data.app }}
      run: |
        set -euo pipefail
        
        # Map GitHub runner arch to Docker platform
        case "$ARCH" in
          x86_64) DOCKER_ARCH=amd64 ;;
          aarch64) DOCKER_ARCH=arm64 ;;
          *) DOCKER_ARCH=$ARCH ;;
        esac
        
        docker run --rm \
          --platform=linux/${DOCKER_ARCH} \
          -e KEY_NAME \
          -e PRIVATE_KEY \
          -e ARCH \
          -e APP_NAME \
          -v "$PWD/${APP_NAME}":/work -w /work \
          alpine:edge sh -euo pipefail -c '

          apk add --no-cache alpine-sdk openssl
          adduser -D -G abuild builder

          mkdir -p /root/.abuild
          printf "%s\n" "$PRIVATE_KEY" > /root/.abuild/$KEY_NAME
          chmod 600 /root/.abuild/$KEY_NAME
          openssl rsa -in /root/.abuild/$KEY_NAME -pubout \
                      -out /etc/apk/keys/${KEY_NAME}.pub

          # Copy keys to builder user
          mkdir -p /home/builder/.abuild
          cp /root/.abuild/$KEY_NAME /home/builder/.abuild/
          chown -R builder:abuild /home/builder/.abuild
          chmod 600 /home/builder/.abuild/$KEY_NAME
          
          chown -R builder:abuild /work
          su builder -c "
            cd /work
            abuild-keygen -a -i -n
            abuild checksum
            abuild -r
          "                  
          outdir=/work/out
          mkdir -p "$outdir"
          find /home/builder/packages -type f -path "*/${ARCH}/*.apk" \
              -exec cp {} "$outdir"/ \;
          [ -n "$(ls -A "$outdir")" ] || { echo "No APKs produced"; exit 1; }
        '

    - name: Upload ${{ matrix.app_data.app }} ${{ matrix.arch }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app_data.app }}-${{ matrix.arch }}-apks
        path: ${{ matrix.app_data.app }}/out/*.apk
        retention-days: 30

  create-releases:
    needs: build-apks
    if: needs.detect-updates.outputs.has_updates == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect-updates.outputs.apps_matrix) }}

    steps:
    - name: Download ${{ matrix.app }} artifacts (both arches)
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ matrix.app }}-*          # matches bazarr-x86_64-apks etc.
        path: artifacts
        merge-multiple: true

    - name: List downloaded APKs
      run: |
        echo "::group::Artifacts for ${{ matrix.app }}"
        find artifacts -name '*.apk' -printf '%P\n'
        echo "::endgroup::"

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name:  ${{ matrix.app }}-v${{ matrix.version }}
        name:      "${{ matrix.app }} v${{ matrix.version }} for Alpine"
        draft:     false
        prerelease: false
        files:     artifacts/*.apk
        body: |
          ## ${{ matrix.app }} v${{ matrix.version }}

          **${{ matrix.description }}**

          Alpine Linux APK packages for multiple architectures.

          ### Installation
          ```bash
          apk add --allow-untrusted ${{ matrix.app }}-${{ matrix.version }}-r0.apk
          ```

          ### Architectures
          - x86_64 (amd64)
          - aarch64 (arm64)

          Built automatically from upstream release:  
          https://github.com/${{ matrix.upstream }}/releases/tag/${{ matrix.version }}
